### ISSUE TITLE
Need a PV for NFS

### ISSUE THREAD

**Issue by John-Lin** [linkernetworks/vortex#246]
We'll have a PV for NFS and it can be bounded with the mongodb statefulset.

The YAML place in `deploy/kubernetes` folder like
```bash
~/go/src/github.com/linkernetworks/vortex/deploy/kubernetes [git::develop] [johnlin@Ches-MacBook-Pro] [0:14]
> tree base
base
|-- hostpath
|   `-- manual.yaml
`-- nfs
    `-- nfs-pv.yaml

3 directories, 1 file
```

The example PV

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-storage 
spec:
  capacity:
    storage: 1Gi 
  accessModes:
  - ReadWriteMany
  nfs: 
    path: /nfsshare 
    server: 10.14.1.100
  persistentVolumeReclaimPolicy: Recycle 
```
We need a PR for making helm YAML and make sure `spec.capacity.storage`, `spec.accessModes`, `spec.nfs.path`, `spec.nfs.server` are configurable
